### ISSUE TITLE
Cannot read property 'startsWith' of undefined 

### ISSUE THREAD

**Issue by abdelrhmanshokr** [sindresorhus/is-up#11]
For some reason this package keeps giving me the error above "Cannot read property 'startsWith' of undefined" even when I copy the code from this repo or from the npm site can anyone help me ? here is my code 

const isUp = require('is-up');

exports.add_a_new_report = async(req, res) => {
    try{
        var url = 'https://google.com';
        console.log(await isUp(url));
    }catch(err){
        return res.status(400).json(err.message);
    }
}

**Comment by sindresorhus** [comment]
What's the stack trace? This package doesn't have any `startsWith` usage.
